#Numpy is nothing but numerical python. It is designed to perform the numerical computation much faster in a highly optimized manner.
#Array or Lists can be used as alternative but won't give the optimized result.

#Numpy is all about matrix computation where even images can be there in a form of matrix only.
#whenever we talk about images and videos/audios everything that we observe internally it get converted into a matrices. So, we must know NumPy.



In [1]:
import numpy as np

In [2]:
arr = np.array([1, 3, 4, 7, 9])
arr

array([1, 3, 4, 7, 9])

In [3]:
arr.ndim

1

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr2 = np.array([[1,3], [7,9]])
arr2

array([[1, 3],
       [7, 9]])

In [6]:
type(arr2)

numpy.ndarray

In [7]:
arr2.ndim

2

In [8]:
arr3 = np.array([[[1,3], [4,7]], [[2,4], [5,7]]])
arr3

array([[[1, 3],
        [4, 7]],

       [[2, 4],
        [5, 7]]])

In [9]:
type(arr3)

numpy.ndarray

In [10]:
arr3.ndim

3

In [11]:
arr3.shape

(2, 2, 2)

In [12]:
arr.shape

(5,)

In [13]:
arr2.shape

(2, 2)

In [14]:
 arr4 = np.array([[[1,3], [4,7]], [[2,4], [5,7]], [[1,9],[3,9]]])
 arr4

array([[[1, 3],
        [4, 7]],

       [[2, 4],
        [5, 7]],

       [[1, 9],
        [3, 9]]])

#Always consider the array from the no. of bracket or else use the arr.shape to find the same. type.array is used for knowing the datatype of the array.
#Always consider the first no. of the arr.ndim is the no. of matrix and remainig will indicate the no. of elemnts in x and y axis of the matrices.

In [15]:
arr4.ndim

3

In [16]:
arr4.shape

(3, 2, 2)

In [17]:
np.arange(1,9)

array([1, 2, 3, 4, 5, 6, 7, 8])

#This function arange will give the o/p in the form of the arrays which starts from first value inside the bracket till the value before the last number.

In [ ]:
np.arange(1,9,2)

array([1, 3, 5, 7])

#Here the integer 2 use to give jump to the no.of array like in this case it is 2 so it will give 1,3,5,7  but not 9 because it greater then n-1 condition of array.

In [18]:
np.linspace(1,9,6)

array([1. , 2.6, 4.2, 5.8, 7.4, 9. ])

#Here the value 6 impact as this will evenly distribute into the given range and it will give the o/p as an array with considering last integer in a bracket unlike arange function.

#What is the difference between the shallow copy and deep copy ?



In [19]:
arr2

array([[1, 3],
       [7, 9]])

In [20]:
shallowarr = arr2

In [21]:
deeparr = np.copy(arr2)

In [22]:
arr2[0][0] = 5
arr2

array([[5, 3],
       [7, 9]])

In [24]:
shallowarr

array([[5, 3],
       [7, 9]])

In [25]:
deeparr

array([[1, 3],
       [7, 9]])

##shallow arr worked as same memory allocated from arr to shallow arr whereas in np.copy  different memory gets created hence changes in shallow arr does not chane deep arr.

#Now we will see  fromfunction in NumPy

In [27]:
np.fromfunction(lambda i,j:i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [31]:
 np.fromfunction(lambda i,j:i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

#So by using this fromfunction we can perform matrix operation with just one line. here we can see that for boolean it shows 'true' whereas in exponential it shows the multiplication of the position of the matrix's element.

In [32]:
np.fromfunction(lambda i,j:i*j, (8,8))

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28.],
       [ 0.,  5., 10., 15., 20., 25., 30., 35.],
       [ 0.,  6., 12., 18., 24., 30., 36., 42.],
       [ 0.,  7., 14., 21., 28., 35., 42., 49.]])

In [33]:
np.fromfunction(lambda i,j:i-j, (6,6))

array([[ 0., -1., -2., -3., -4., -5.],
       [ 1.,  0., -1., -2., -3., -4.],
       [ 2.,  1.,  0., -1., -2., -3.],
       [ 3.,  2.,  1.,  0., -1., -2.],
       [ 4.,  3.,  2.,  1.,  0., -1.],
       [ 5.,  4.,  3.,  2.,  1.,  0.]])

#Wants to create an identity matrix :- square matix with one's in diagonal
#eye is the keyword

In [34]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#Reshape function in NumPy

In [52]:
dataset = np.linspace(2,9,50)
dataset

array([2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
       2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
       3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
       4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
       4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143,
       5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
       6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
       7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
       7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
       8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ])

In [46]:
dataset2 = np.linspace(1,8,50)
dataset2

array([1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
       1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
       2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
       3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
       3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143,
       4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
       5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
       6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
       6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
       7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ])

In [53]:
 dataset.shape

(50,)

In [50]:
dataset2.shape

(50,)

#dataset.shape is a function to crosscheck the linspace function has divided the range in by given value or not.

In [48]:
dataset2.reshape(2,1,25)

array([[[1.        , 1.14285714, 1.28571429, 1.42857143, 1.57142857,
         1.71428571, 1.85714286, 2.        , 2.14285714, 2.28571429,
         2.42857143, 2.57142857, 2.71428571, 2.85714286, 3.        ,
         3.14285714, 3.28571429, 3.42857143, 3.57142857, 3.71428571,
         3.85714286, 4.        , 4.14285714, 4.28571429, 4.42857143]],

       [[4.57142857, 4.71428571, 4.85714286, 5.        , 5.14285714,
         5.28571429, 5.42857143, 5.57142857, 5.71428571, 5.85714286,
         6.        , 6.14285714, 6.28571429, 6.42857143, 6.57142857,
         6.71428571, 6.85714286, 7.        , 7.14285714, 7.28571429,
         7.42857143, 7.57142857, 7.71428571, 7.85714286, 8.        ]]])

In [54]:
dataset.reshape(2,1,25)

array([[[2.        , 2.14285714, 2.28571429, 2.42857143, 2.57142857,
         2.71428571, 2.85714286, 3.        , 3.14285714, 3.28571429,
         3.42857143, 3.57142857, 3.71428571, 3.85714286, 4.        ,
         4.14285714, 4.28571429, 4.42857143, 4.57142857, 4.71428571,
         4.85714286, 5.        , 5.14285714, 5.28571429, 5.42857143]],

       [[5.57142857, 5.71428571, 5.85714286, 6.        , 6.14285714,
         6.28571429, 6.42857143, 6.57142857, 6.71428571, 6.85714286,
         7.        , 7.14285714, 7.28571429, 7.42857143, 7.57142857,
         7.71428571, 7.85714286, 8.        , 8.14285714, 8.28571429,
         8.42857143, 8.57142857, 8.71428571, 8.85714286, 9.        ]]])

#reshape helps to find the patterns indside the images so multiple matrix's multiplication is required. Hence, reshape is used. Here if a matrix is A*B then other one should be a B*C so that the matrix calxulation can be done relatively accurate and find out the same exact result.
#Always remeber the number while reshaping must be exactly multiplicable to the given number so that it cannot show the value error.